name: Build and publish

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: ["10.0.4"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@main
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
          distribution: 'temurin'
      - uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}
      - uses: actions/checkout@v2
        with:
          repository: astrelsky/Ghidra-Cpp-Class-Analyzer
          path: Ghidra-Cpp-Class-Analyzer
      - uses: eskatos/gradle-command-action@v2
        with:
          gradle-version: 6.9
          build-root-directory: Ghidra-Cpp-Class-Analyzer
          arguments: buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
      - name: Install the class analyzer as an extension forcefully
        run: |
           mkdir -p ~/.ghidra/.ghidra_${{ matrix.ghidra }}_PUBLIC/Extensions/
           unzip Ghidra-Cpp-Class-Analyzer/dist/*.zip -d ~/.ghidra/.ghidra_${{ matrix.ghidra }}_PUBLIC/Extensions/
      - uses: actions/upload-artifact@v2
        with:
          name: Ghidra-Cpp-Class-Analyzer
          path: Ghidra-Cpp-Class-Analyzer/dist/*.zip
          if-no-files-found: warn
      - name: Cleanup
        run: rm -rf Ghidra-Cpp-Class-Analyzer
      - uses: eskatos/gradle-command-action@v2
        with:
          gradle-version: 6.9
          arguments: buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
      - uses: actions/upload-artifact@v2
        with:
          name: GhidraOrbis
          path: dist/*.zip
          if-no-files-found: warn


